/** @format */

export const SEARCHED_RECIPES = "FETCHED_NEW_RECIPES_BY_NAME";

export const GET_COCKTAILS_BY_INGREDIENTS = "GET_COCKTAILS_BY_INGREDIENTS";

export const ADD_FAV_COCKTAIL = "ADD_FAVORITE_COCKTAIL";

export const REMOVE_FAV_COCKTAIL = "REMOVE_FAVORITE_COCKTAIL";

export const FETCH_FAV_COCKTAIL_ID = "FETCH_FAV_COCKTAIL_ID";

export const TOGGLE_FAV_COCKTAIL = "TOGGLE_FAV_COCKTAIL";
