/** @format */

export const SEARCHED_INGREDIENTS = 'FETCHED_NEW_INGREDIENTS_BY_NAME';

export const REMOVE_INGREDIENT_FROM_SEARCH_BY =
  'REMOVE_INGREDIENT_FROM_SEARCH_BY_ADDED_INGREDIENTS';

export const ADD_INGREDIENT_TO_SEARCH_BY =
  'ADD_INGREDIENT_TO_SEARCH_BY_ADDED_INGREDIENTS';

export const ADDED_CHECK_MAP_UPDATE = 'ADDED_CHECK_MAP_UPDATE';

export const GET_INVENTORY_INGS = 'GET_BACK_END_INGS';

export const SAVE_INVENTORY_INGS = 'SAVE_BACK_END_INGS';
