export const SEARCHED_INGREDIENTS = "FETCHED_NEW_INGREDIENTS_BY_NAME"

export const REMOVE_INGREDIENT_FROM_SEARCH_BY = "REMOVE_INGREDIENT_FROM_SEARCH_BY_ADDED_INGREDIENTS"

export const ADD_INGREDIENT_TO_SEARCH_BY = "ADD_INGREDIENT_TO_SEARCH_BY_ADDED_INGREDIENTS"

