/** @format */

export const ADD_TOKEN = "GET_TOKEN";

export const GOOGLE_SIGN_IN = "GOOGLE_SIGN_IN_SUCCESS";

export const GOOGLE_FULL_SIGN_IN = "GOOGLE_FULL_SIGN_IN";

export const APPLE_FULL_SIGN_IN = "APPLE_FULL_SIGN_IN";

export const LOG_OUT = "LOG_OUT";

export const TOGGLE_THEME = "TOGGLE_THEME";

export const CACHE_SIGN_IN = "USER_FETCHED_FROM_LOCAL_STORAGE";

export const USER_CACHE_CLEANED = "USER_CACHE_CLEANED";

export const USER_CACHE_CLEANED_ERROR = "USER_CACHE_CLEANED_ERROR";

export const FETCHED_INTERSTITIAL_AD_RATIO = "FETCHED_INTERSTITIAL_AD_RATIO";
