name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Running ESlint and building
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
          
      - name: Install
        run: npm ci

      - name: Lint
        uses: eslint/github-action@v0
      
      - name: Test
        run: |
          npm test
          expo doctor

      - name: Build
        run: expo publish
      
