# @format

name: Build and publish preview
on:
  - pull_request

jobs:
  build:
    name: Install, publish and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true

      - name: Install
        run: npm ci

      - name: Run ESLint
        uses: stefanoeb/eslint-action@1.0.2

      - name: Test
        run: |
          npm test
          expo doctor

      - name: Publish Expo App
        run: expo publish --release-channel=pr-${{ github.event.number }}

      - name: Build binaries for IOS
        run: expo build:ios --release-channel pr-${{ github.event.number }}

      - name: Build binaries for Android
        run: expo build:android --release-channel pr-${{ github.event.number }}

      - name: Get Expo App link
        id: expo
        run: echo "::set-output name=path::@beornot2be/cocktailbuilderApp?release-channel=pr-${{ github.event.number }}"

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: Try running it on [Mobile](https://expo.io/${{ steps.expo.outputs.path }})<br><br><a href="https://exp.host/${{ steps.expo.outputs.path }}"><img src="https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=exp://exp.host/${{ steps.expo.outputs.path }}" height="200px" width="200px"></a>.
